<?xml version="1.0" encoding="utf-8"?><Database Name="MoneyManager" Class="MoneyManagerDataClassDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=WINDELL-EG5KDM3\SQLEXPRESS;Initial Catalog=MoneyManager;Integrated Security=True" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="MoneyManagerConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.MONTHS" Member="MONTHs">
    <Type Name="MONTH">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MonthName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TYPESOFEXPANSE" Member="TYPESOFEXPANSEs">
    <Type Name="TYPESOFEXPANSE">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TypeOfExpanse" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.USERS" Member="USERs">
    <Type Name="USER">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="InitialMoney" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.YEARS" Member="YEARs">
    <Type Name="YEAR">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="YearNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TYPE_INCOME_EXPANSE" Member="TYPE_INCOME_EXPANSEs">
    <Type Name="TYPE_INCOME_EXPANSE">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[Income/Expanse]" Member="Income_Expanse" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.POSITIONS" Member="POSITIONs">
    <Type Name="POSITION">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TypeOfExpanseID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Amount of Expanse]" Member="Amount_of_Expanse" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="YearID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MonthID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Income/ExpnaseID]" Member="Income_ExpnaseID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Income/ExpansePosition]" Member="Income_ExpansePosition" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.YearOverview" Member="YearOverviews">
    <Type Name="YearOverview">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TypeOfExpanseID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Total" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Average" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Income/ExpnaseID]" Member="Income_ExpnaseID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Income/ExpansePosition]" Member="Income_ExpansePosition" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="YearID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>